{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ui-ingress
spec:
  podSelector:
    matchLabels:
      {{- include "pharmacy-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ui-to-backend
spec:
  podSelector:
    matchLabels:
      {{- include "pharmacy-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  policyTypes: ["Egress"]
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "pharmacy-platform.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: backend
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-from-ui
spec:
  podSelector:
    matchLabels:
      {{- include "pharmacy-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "pharmacy-platform.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: ui
      ports:
        - protocol: TCP
          port: 8080
{{- if .Values.database.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-to-database
spec:
  podSelector:
    matchLabels:
      {{- include "pharmacy-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  policyTypes: ["Egress"]
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "pharmacy-platform.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: database
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-from-backend
spec:
  podSelector:
    matchLabels:
      {{- include "pharmacy-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "pharmacy-platform.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: backend
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
{{- end }}
