apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.workloadIdentity.serviceAccountName }}
  labels:
    {{- include "pharmacy-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if .Values.backend.workloadIdentity.clientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.backend.workloadIdentity.clientId | quote }}
  {{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui
  labels:
    {{- include "pharmacy-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
automountServiceAccountToken: false
