ui:
  replicas: 1
  image:
    tag: prod
  pdb:
    enabled: false

backend:
  replicas: 1
  image:
    tag: prod
  pdb:
    enabled: false
  database:
    server: sql-azplab-d45c2a33.database.windows.net
    name: pharmacy-prod

gateway:
  enabled: true
  hostname: pharmacy.test
