ui:
  image:
    tag: dev

backend:
  image:
    tag: dev
  database:
    server: sql-azplab-d45c2a33.database.windows.net
    name: pharmacy-dev

gateway:
  enabled: true
  hostname: dev.4-223-16-69.nip.io
