ui:
  replicas: 2
  image:
    tag: prod
  pdb:
    enabled: true

backend:
  replicas: 2
  image:
    tag: prod
  pdb:
    enabled: true
  database:
    server: sql-azplab-d45c2a33.database.windows.net
    name: pharmacy-prod
